In [1]:
import numpy
import pandas

In [2]:
data = pandas.read_csv("loan_train.csv")
df = pandas.DataFrame(data)
df

,Gender,Married,Dependents,Education,Self_Employed,Applicant_Income,Coapplicant_Income,Loan_Amount,Term,Credit_History,Area,Status
0,Male,No,0,Graduate,No,584900,0.0,15000000,360.0,1.0,Urban,Y
1,Male,Yes,1,Graduate,No,458300,150800.0,12800000,360.0,1.0,Rural,N
2,Male,Yes,0,Graduate,Yes,300000,0.0,6600000,360.0,1.0,Urban,Y
3,Male,Yes,0,Not Graduate,No,258300,235800.0,12000000,360.0,1.0,Urban,Y
4,Male,No,0,Graduate,No,600000,0.0,14100000,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
609,Female,No,0,Graduate,No,290000,0.0,7100000,360.0,1.0,Rural,Y
610,Male,Yes,3+,Graduate,No,410600,0.0,4000000,180.0,1.0,Rural,Y
611,Male,Yes,1,Graduate,No,807200,24000.0,25300000,360.0,1.0,Urban,Y
612,Male,Yes,2,Graduate,No,758300,0.0,18700000,360.0,1.0,Urban,Y
613,Female,No,0,Graduate,Yes,458300,0.0,13300000,360.0,0.0,Semiurban,N

In [3]:
# target >>> Status

In [4]:
df = df.drop(columns=['Gender','Married'])
df

,Dependents,Education,Self_Employed,Applicant_Income,Coapplicant_Income,Loan_Amount,Term,Credit_History,Area,Status
0,0,Graduate,No,584900,0.0,15000000,360.0,1.0,Urban,Y
1,1,Graduate,No,458300,150800.0,12800000,360.0,1.0,Rural,N
2,0,Graduate,Yes,300000,0.0,6600000,360.0,1.0,Urban,Y
3,0,Not Graduate,No,258300,235800.0,12000000,360.0,1.0,Urban,Y
4,0,Graduate,No,600000,0.0,14100000,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...
609,0,Graduate,No,290000,0.0,7100000,360.0,1.0,Rural,Y
610,3+,Graduate,No,410600,0.0,4000000,180.0,1.0,Rural,Y
611,1,Graduate,No,807200,24000.0,25300000,360.0,1.0,Urban,Y
612,2,Graduate,No,758300,0.0,18700000,360.0,1.0,Urban,Y
613,0,Graduate,Yes,458300,0.0,13300000,360.0,0.0,Semiurban,N

In [5]:
df.isna().sum()

Dependents            15
Education              0
Self_Employed         32
Applicant_Income       0
Coapplicant_Income     0
Loan_Amount            0
Term                  14
Credit_History        50
Area                   0
Status                 0
dtype: int64

In [6]:
df.dtypes

Dependents             object
Education              object
Self_Employed          object
Applicant_Income        int64
Coapplicant_Income    float64
Loan_Amount             int64
Term                  float64
Credit_History        float64
Area                   object
Status                 object
dtype: object

In [7]:
df['Dependents'] = df['Dependents'].fillna(df['Dependents'].mode()[0])
df

,Dependents,Education,Self_Employed,Applicant_Income,Coapplicant_Income,Loan_Amount,Term,Credit_History,Area,Status
0,0,Graduate,No,584900,0.0,15000000,360.0,1.0,Urban,Y
1,1,Graduate,No,458300,150800.0,12800000,360.0,1.0,Rural,N
2,0,Graduate,Yes,300000,0.0,6600000,360.0,1.0,Urban,Y
3,0,Not Graduate,No,258300,235800.0,12000000,360.0,1.0,Urban,Y
4,0,Graduate,No,600000,0.0,14100000,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...
609,0,Graduate,No,290000,0.0,7100000,360.0,1.0,Rural,Y
610,3+,Graduate,No,410600,0.0,4000000,180.0,1.0,Rural,Y
611,1,Graduate,No,807200,24000.0,25300000,360.0,1.0,Urban,Y
612,2,Graduate,No,758300,0.0,18700000,360.0,1.0,Urban,Y
613,0,Graduate,Yes,458300,0.0,13300000,360.0,0.0,Semiurban,N

In [8]:
df.isna().sum()

Dependents             0
Education              0
Self_Employed         32
Applicant_Income       0
Coapplicant_Income     0
Loan_Amount            0
Term                  14
Credit_History        50
Area                   0
Status                 0
dtype: int64

In [9]:
df['Self_Employed'] = df['Self_Employed'].fillna(df['Self_Employed'].mode()[0])
df

,Dependents,Education,Self_Employed,Applicant_Income,Coapplicant_Income,Loan_Amount,Term,Credit_History,Area,Status
0,0,Graduate,No,584900,0.0,15000000,360.0,1.0,Urban,Y
1,1,Graduate,No,458300,150800.0,12800000,360.0,1.0,Rural,N
2,0,Graduate,Yes,300000,0.0,6600000,360.0,1.0,Urban,Y
3,0,Not Graduate,No,258300,235800.0,12000000,360.0,1.0,Urban,Y
4,0,Graduate,No,600000,0.0,14100000,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...
609,0,Graduate,No,290000,0.0,7100000,360.0,1.0,Rural,Y
610,3+,Graduate,No,410600,0.0,4000000,180.0,1.0,Rural,Y
611,1,Graduate,No,807200,24000.0,25300000,360.0,1.0,Urban,Y
612,2,Graduate,No,758300,0.0,18700000,360.0,1.0,Urban,Y
613,0,Graduate,Yes,458300,0.0,13300000,360.0,0.0,Semiurban,N

In [10]:
df['Term'] = df['Term'].fillna(df['Term'].mean())
df

,Dependents,Education,Self_Employed,Applicant_Income,Coapplicant_Income,Loan_Amount,Term,Credit_History,Area,Status
0,0,Graduate,No,584900,0.0,15000000,360.0,1.0,Urban,Y
1,1,Graduate,No,458300,150800.0,12800000,360.0,1.0,Rural,N
2,0,Graduate,Yes,300000,0.0,6600000,360.0,1.0,Urban,Y
3,0,Not Graduate,No,258300,235800.0,12000000,360.0,1.0,Urban,Y
4,0,Graduate,No,600000,0.0,14100000,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...
609,0,Graduate,No,290000,0.0,7100000,360.0,1.0,Rural,Y
610,3+,Graduate,No,410600,0.0,4000000,180.0,1.0,Rural,Y
611,1,Graduate,No,807200,24000.0,25300000,360.0,1.0,Urban,Y
612,2,Graduate,No,758300,0.0,18700000,360.0,1.0,Urban,Y
613,0,Graduate,Yes,458300,0.0,13300000,360.0,0.0,Semiurban,N

In [11]:
df['Credit_History'] = df['Credit_History'].fillna(df['Credit_History'].mean())
df

,Dependents,Education,Self_Employed,Applicant_Income,Coapplicant_Income,Loan_Amount,Term,Credit_History,Area,Status
0,0,Graduate,No,584900,0.0,15000000,360.0,1.0,Urban,Y
1,1,Graduate,No,458300,150800.0,12800000,360.0,1.0,Rural,N
2,0,Graduate,Yes,300000,0.0,6600000,360.0,1.0,Urban,Y
3,0,Not Graduate,No,258300,235800.0,12000000,360.0,1.0,Urban,Y
4,0,Graduate,No,600000,0.0,14100000,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...
609,0,Graduate,No,290000,0.0,7100000,360.0,1.0,Rural,Y
610,3+,Graduate,No,410600,0.0,4000000,180.0,1.0,Rural,Y
611,1,Graduate,No,807200,24000.0,25300000,360.0,1.0,Urban,Y
612,2,Graduate,No,758300,0.0,18700000,360.0,1.0,Urban,Y
613,0,Graduate,Yes,458300,0.0,13300000,360.0,0.0,Semiurban,N

In [12]:
df.isna().sum()

Dependents            0
Education             0
Self_Employed         0
Applicant_Income      0
Coapplicant_Income    0
Loan_Amount           0
Term                  0
Credit_History        0
Area                  0
Status                0
dtype: int64

In [13]:
df.dtypes

Dependents             object
Education              object
Self_Employed          object
Applicant_Income        int64
Coapplicant_Income    float64
Loan_Amount             int64
Term                  float64
Credit_History        float64
Area                   object
Status                 object
dtype: object

In [14]:
# Encoding

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Dependents'] = le.fit_transform(df['Dependents'])
df['Education'] = le.fit_transform(df['Education'])
df['Self_Employed'] = le.fit_transform(df['Self_Employed'])
df['Area'] = le.fit_transform(df['Area'])
df['Status'] = le.fit_transform(df['Status'])
df

,Dependents,Education,Self_Employed,Applicant_Income,Coapplicant_Income,Loan_Amount,Term,Credit_History,Area,Status
0,0,0,0,584900,0.0,15000000,360.0,1.0,2,1
1,1,0,0,458300,150800.0,12800000,360.0,1.0,0,0
2,0,0,1,300000,0.0,6600000,360.0,1.0,2,1
3,0,1,0,258300,235800.0,12000000,360.0,1.0,2,1
4,0,0,0,600000,0.0,14100000,360.0,1.0,2,1
...,...,...,...,...,...,...,...,...,...,...
609,0,0,0,290000,0.0,7100000,360.0,1.0,0,1
610,3,0,0,410600,0.0,4000000,180.0,1.0,0,1
611,1,0,0,807200,24000.0,25300000,360.0,1.0,2,1
612,2,0,0,758300,0.0,18700000,360.0,1.0,2,1
613,0,0,1,458300,0.0,13300000,360.0,0.0,1,0

In [15]:
X = df.iloc[:,:-1]
X
Y = df.iloc[:,-1]
Y

0      1
1      0
2      1
3      1
4      1
      ..
609    1
610    1
611    1
612    1
613    0
Name: Status, Length: 614, dtype: int64

In [16]:
# Splitting

from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3)
X_train

,Dependents,Education,Self_Employed,Applicant_Income,Coapplicant_Income,Loan_Amount,Term,Credit_History,Area
576,0,0,0,308700,221000.0,13600000,360.0,0.0,1
319,1,0,1,1000000,0.0,15500000,360.0,1.0,0
498,1,0,1,289500,0.0,9500000,360.0,1.0,1
401,0,1,0,275500,0.0,6500000,300.0,1.0,0
249,0,0,0,180900,186800.0,9000000,360.0,1.0,2
...,...,...,...,...,...,...,...,...,...
287,0,0,0,370400,200000.0,12000000,360.0,1.0,0
40,0,0,0,360000,0.0,8000000,360.0,1.0,2
426,1,1,0,460600,0.0,8100000,360.0,1.0,0
217,0,0,0,372700,177500.0,13100000,360.0,1.0,1
370,0,0,1,1575900,0.0,5500000,360.0,1.0,1

In [17]:
# Scaling

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [18]:
# Model generation

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()

model = knn.fit(X_train,Y_train)

In [19]:
# Prediction

y_pred = model.predict(X_test)

In [20]:
# Accuracy

from sklearn.metrics import accuracy_score

print(accuracy_score(Y_test,y_pred))

0.8

In [21]:
# Confusion Matrix

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Y_test,y_pred)
cm

array([[ 32,  30],
       [  7, 116]])