In [1]:
import pandas
import openpyxl

In [2]:
data = pandas.read_excel('Online Retail.xlsx')
df = pandas.DataFrame(data)
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [3]:
df.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [4]:
df = df.dropna(subset=['CustomerID'])
df.isna().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [5]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [6]:
df.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

In [7]:
df = df.drop(columns=['InvoiceNo','StockCode','InvoiceDate','Description'],axis=1)

In [8]:
df.dtypes

Quantity        int64
UnitPrice     float64
CustomerID    float64
Country        object
dtype: object

In [9]:
df

        Quantity  UnitPrice  CustomerID         Country
0              6       2.55     17850.0  United Kingdom
1              6       3.39     17850.0  United Kingdom
2              8       2.75     17850.0  United Kingdom
3              6       3.39     17850.0  United Kingdom
4              6       3.39     17850.0  United Kingdom
...          ...        ...         ...             ...
541904        12       0.85     12680.0          France
541905         6       2.10     12680.0          France
541906         4       4.15     12680.0          France
541907         4       4.15     12680.0          France
541908         3       4.95     12680.0          France

[406829 rows x 4 columns]

In [10]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Country'] = le.fit_transform(df['Country'])

df

        Quantity  UnitPrice  CustomerID  Country
0              6       2.55     17850.0       35
1              6       3.39     17850.0       35
2              8       2.75     17850.0       35
3              6       3.39     17850.0       35
4              6       3.39     17850.0       35
...          ...        ...         ...      ...
541904        12       0.85     12680.0       13
541905         6       2.10     12680.0       13
541906         4       4.15     12680.0       13
541907         4       4.15     12680.0       13
541908         3       4.95     12680.0       13

[406829 rows x 4 columns]

In [11]:
X = df.drop(columns=['Country'],axis=1)
Y = df['Country']

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3)

In [13]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(X_train)

X_test = sc.transform(X_test)

In [14]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

model = lr.fit(X_train, Y_train)

Y_pred = model.predict(X_test)

In [15]:
from sklearn.metrics import mean_absolute_percentage_error,r2_score

print(mean_absolute_percentage_error(Y_test,Y_pred))
print(r2_score(Y_test,Y_pred))

386956130234133.25
0.14768866866402863