In [130]:
import numpy
import pandas

In [131]:
data = pandas.read_csv('youth_unemployment_global.csv')
df = pandas.DataFrame(data)
df

                           Country CountryCode  Year  YouthUnemployment
0      Africa Eastern and Southern          ZH  2024          13.283002
1      Africa Eastern and Southern          ZH  2023          13.367810
2      Africa Eastern and Southern          ZH  2022          13.620217
3      Africa Eastern and Southern          ZH  2021          14.955182
4      Africa Eastern and Southern          ZH  2020          14.997030
...                            ...         ...   ...                ...
17285                     Zimbabwe          ZW  1964                NaN
17286                     Zimbabwe          ZW  1963                NaN
17287                     Zimbabwe          ZW  1962                NaN
17288                     Zimbabwe          ZW  1961                NaN
17289                     Zimbabwe          ZW  1960                NaN

[17290 rows x 4 columns]

In [132]:
df.isna().sum()

Country                 0
CountryCode            65
Year                    0
YouthUnemployment    9309
dtype: int64

In [133]:
df = df.dropna(subset=['YouthUnemployment'])
df = df.dropna(subset=['CountryCode'])
df

                           Country CountryCode  Year  YouthUnemployment
0      Africa Eastern and Southern          ZH  2024          13.283002
1      Africa Eastern and Southern          ZH  2023          13.367810
2      Africa Eastern and Southern          ZH  2022          13.620217
3      Africa Eastern and Southern          ZH  2021          14.955182
4      Africa Eastern and Southern          ZH  2020          14.997030
...                            ...         ...   ...                ...
17254                     Zimbabwe          ZW  1995          12.241000
17255                     Zimbabwe          ZW  1994          10.872000
17256                     Zimbabwe          ZW  1993          10.972000
17257                     Zimbabwe          ZW  1992          10.919000
17258                     Zimbabwe          ZW  1991          10.667000

[7947 rows x 4 columns]

In [134]:
df.dtypes

Country               object
CountryCode           object
Year                   int64
YouthUnemployment    float64
dtype: object

In [135]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Country'] = le.fit_transform(df['Country'])
df['CountryCode'] = le.fit_transform(df['CountryCode'])

In [136]:
df

       Country  CountryCode  Year  YouthUnemployment
0            1          227  2024          13.283002
1            1          227  2023          13.367810
2            1          227  2022          13.620217
3            1          227  2021          14.955182
4            1          227  2020          14.997030
...        ...          ...   ...                ...
17254      233          233  1995          12.241000
17255      233          233  1994          10.872000
17256      233          233  1993          10.972000
17257      233          233  1992          10.919000
17258      233          233  1991          10.667000

[7947 rows x 4 columns]

In [137]:
X = df.iloc[:,:-1]
Y = df.iloc[:,-1]

In [138]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3)

In [ ]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(X_train)

X_test = sc.transform(X_test)

In [140]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()

model = lr.fit(X_train,Y_train)

Y_pred = model.predict(X_test)

ValueError: Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.

In [ ]:
from sklearn.metrics import mean_absolute_percentage_error,r2_score

print(mean_absolute_percentage_error(Y_test,Y_pred))
print(r2_score(Y_test,Y_pred))

1.106806573572637
0.016198509252312254