In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('Telecust1.csv')

df = pd.DataFrame(data)

df

,region,tenure,age,income,marital,address,ed,employ,retire,gender,reside,custcat
0,2,13,44,64,1,9,4,5,0,0,2,A
1,3,11,33,136,1,7,5,5,0,0,6,D
2,3,68,52,116,1,24,1,29,0,1,2,C
3,2,33,33,33,0,12,2,0,0,1,1,A
4,2,23,30,30,1,9,1,2,0,0,4,C
...,...,...,...,...,...,...,...,...,...,...,...,...
995,3,10,39,27,0,0,3,0,0,1,3,A
996,1,7,34,22,0,2,5,5,0,1,1,A
997,3,67,59,944,0,40,5,33,0,1,1,D
998,3,70,49,87,0,18,2,22,0,1,1,C
999,3,50,36,39,1,7,3,3,0,1,3,B

In [3]:
df.isna().sum()

region     0
tenure     0
age        0
income     0
marital    0
address    0
ed         0
employ     0
retire     0
gender     0
reside     0
custcat    0
dtype: int64

In [4]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['custcat'] = le.fit_transform(df['custcat'])
df.dtypes

region     int64
tenure     int64
age        int64
income     int64
marital    int64
address    int64
ed         int64
employ     int64
retire     int64
gender     int64
reside     int64
custcat    int64
dtype: object

In [5]:
X = df.iloc[:,:-1]
Y = df.iloc[:,-1]
X

,region,tenure,age,income,marital,address,ed,employ,retire,gender,reside
0,2,13,44,64,1,9,4,5,0,0,2
1,3,11,33,136,1,7,5,5,0,0,6
2,3,68,52,116,1,24,1,29,0,1,2
3,2,33,33,33,0,12,2,0,0,1,1
4,2,23,30,30,1,9,1,2,0,0,4
...,...,...,...,...,...,...,...,...,...,...,...
995,3,10,39,27,0,0,3,0,0,1,3
996,1,7,34,22,0,2,5,5,0,1,1
997,3,67,59,944,0,40,5,33,0,1,1
998,3,70,49,87,0,18,2,22,0,1,1
999,3,50,36,39,1,7,3,3,0,1,3

In [6]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42,stratify=Y)
X_train

,region,tenure,age,income,marital,address,ed,employ,retire,gender,reside
564,3,66,55,80,0,20,2,24,0,1,1
801,2,22,28,36,1,0,4,0,0,0,4
607,1,35,34,78,0,7,4,10,0,1,1
882,2,31,46,144,0,23,4,13,0,0,1
535,3,31,34,105,0,9,4,7,0,1,4
...,...,...,...,...,...,...,...,...,...,...,...
849,3,65,56,608,1,19,3,34,0,1,2
873,3,54,32,27,1,12,1,9,0,0,2
719,2,19,32,71,0,12,4,5,0,1,1
252,1,52,54,153,1,5,5,10,0,0,2
263,3,70,53,183,1,16,2,35,0,1,2

In [7]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

knn = KNeighborsClassifier(n_neighbors=5)
nb = GaussianNB()
dt = DecisionTreeClassifier(max_depth=5, random_state=42)
rf = RandomForestClassifier(n_estimators=100, random_state=42)

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import StackingClassifier

estimators = [('knn',knn),('nb',nb),('dt',dt),('rf',rf)]

stackmodel = StackingClassifier(
    estimators=estimators,
    final_estimator=LogisticRegression(),
    cv=5
)

In [ ]:
from sklearn.metrics import accuracy_score

stackmodel.fit(X_train,Y_train)

y_pred = stackmodel.predict((X_test))

print(accuracy_score(Y_test,y_pred)*100)

365.0